version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
      - '3000:3000'
    volumes:
      - ./server:/app/server
      - ./client:/app/client